version: '3.8'

services:
  nextapp:
    build: .
    container_name: next_app
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
    command: [ "npm", "run", "dev", "--", "-p", "3001" ]
